spring.application.name=granttrack

spring.datasource.url=jdbc:mysql://localhost:3306/granttrack-db
spring.datasource.username=root
spring.datasource.password=ishuraja24@2007

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081